export const quotes = [
  "been on a date 💕",
  "been in a relationship 🥰",
  "kissed a mps (member of the preferred sex) 😘",
  "made out in public 😐",
  "played a game involved stripping 🩲",
  "masturbated 😈",
  "sent or received underwear pics 👙",
  "sent nudes 🚫",
  "received nudes ❌",
  "sexted 📲",
  "facetime sex 🤳",
  "kissed 3 or more people in one night. 👨‍👩‍👦",
  "FwB 👩🏼‍🤝‍👨🏽",
  "been in love 💖",
  "had a dating app 🔥",
  "paid for a premium version of a dating app 💸",
  "long distance relationship 🛫",
  "asked for a stranger’s contact info #️⃣",
  "been asked for your contact info by a stranger 👻",
  "gotten back with/hooked up with an ex ❎",
  "slid into someone’s DMs 📳",
  "watched porn 🟧⬛️",
  "paid for any porn 🤑",
  "watched porn with mps 🍿",
  "talked to 5 or more people at once 5️⃣",
  "posted a thirst trap 😜",
  "said “i love you” 😍",
  "been to a party 🎉",
  "thrown a party 🥳",
  "drank 🥂",
  "been drunk 😵",
  "blacked or yakked 🥴",
  "played a drinking game 🥤",
  "faked sobriety 🤥",
  "flirted with a stranger to get a free drink 🍻",
  "taken alcohol from your parents 🥃",
  "smoked weed 🍃",
  "done edibles 🍪",
  "hit a bong ⚗️",
  "nicotine (vaped) 💨",
  "smoked a cigarette 🚬",
  "cocaine or a drug stronger 💉",
  "had a fake 🆔",
  "had a fake ID confiscated 👮‍♂️",
  "used a fake to buy alcohol/drugs 💰",
  "used a fake to get into a bar/club 🕺",
  "had the police called on you 🚔",
  "gotten in trouble with school or law 🙁",
  "showered with mps 🚿",
  "given/received a hickey 💋",
  "had/given blue balls 🔵",
  "someone else made you orgasm 🤯",
  "cheated/been cheated on/been cheated with 🤮",
  "bought plan b 👼🏼",
  "bought birth control 💊",
  "given head 🧠",
  "received head 👄",
  "used a sex toy 🧸",
  "spent the night with mps 💤",
  "been walked in on while engaging in a sexual act 😳",
  "sexiled a roommate 👋🏼",
  "had sex 🍆",
  "had sex 3 or more times in one night. 🏘",
  "STI/STD test 🦠",
  "had car sex 🚘",
  "had sex in public 📢",
  "used blindfold/handcuffs in bed 🤭",
  "joined the mile high club 🛫",
  "❓",
  "3some 3️⃣",
  "orgy! 🔢",
  "body count > 5 📈",
  "sex tape. 🎥",
  "anal 🍑",
  "period sex 🩸",
  "bought a pregnancy test 📄",
  "been preggo/ gotten someone preggo 🤰",
  "streaked 👀",
  "skinny dipped 🌊",
  "seen a stripper 👅",
  "run from the police 👮",
  "been questioned by/handcuffed by police 🚨",
  "committed vandalism 🎨",
  "driven under the influence 🚙",
  "texted while driving 💬",
  "gotten a tattoo 🖋️",
  "pierced something other than your ears 👃",
  "stolen something 💲",
  "crashed a car 🏎",
  "blocked someone on social media 👎🏽",
  "gotten kicked out of a party 😡",
  "been at a party that got raided 🚒",
  "snuck out 😰",
  "had corona! 😷",
  "had a crush on a teacher 👩‍🏫",
  "stalked someone’s snapchat location 📍",
  "gotten with 2+ people in the same friend group 👏🏼",
  "whole snap best friends list has been love interests 😎",
  "gotten with someone 3+ years older than you 👵",
  "gotten with someone 3+ years younger than you 👶",
];
