import type { NextPage } from "next";
import Head from "next/head";
import Title from "../components/title";

const Home: NextPage = () => {
  return (
    <div className="border-4 border-red-500">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title />
    </div>
  );
};

export default Home;
